# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr:
- master

stages:
  - stage: print
    jobs:
      - job: helloworld
        displayName: "Print-Hello"
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: echo Hello, world!
