parameters:
  - name: artifactName
    type: string
  - name: scanPattern
    type: string
    
jobs:
  - job: cfn_lint
    displayName: "Scan the template via Cfn Lint"
    pool:
      vmImage: ubuntu-latest
      
    steps:
      - checkout: none
      
      - download: current
        artifact: ${{parameters.artifactName}}
        
      - task: UsePythonVersion@0
        displayName: "Set Python Version"
        inputs:
          versionSpec: $(cfn_lint_python_version)
          
      - script: pip install cfn-lint
        displayName: "Install cfn-lint"
        
      - script: cfn-lint $(Pipeline.Workspace)/${{parameters.artifactName}}/${{scan.Pattern}} --info
        displayName: "Run cfn-lint"
